FROM nginx:latest

# Copie les fichiers du site web
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

# Copie la configuration Nginx
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
